### ISSUE TITLE
Can not start plugin last version 1.0.9

### ISSUE THREAD

**Issue by erwan2345** [Smanar/Domoticz-deCONZ#25]
Plugin 1.0.7 was working fine but I tried the last one 1.0.9 and it does not start, domoticz log error display that:

2019-07-20 19:13:42.969 Error: (deCONZ) failed to load 'plugin.py', Python Path used was '/home/applications/domoticz/plugins/Domoticz-deCONZ/:/usr/lib/python3.4/:/usr/lib/python3.4/plat-arm-linux-gnueabihf:/usr/lib/python3.4/lib-dynload'.
2019-07-20 19:13:42.969 Error: (deCONZ) Module Import failed, exception: 'ImportError'
2019-07-20 19:13:42.969 Error: (deCONZ) Module Import failed: ' Name: requests'
2019-07-20 19:13:42.969 Error: (deCONZ) Error Line details not available.

It is running on Raspberry Pi 3 , python --version returns Python 2.7.9

**Comment by Smanar** [comment]
Hello, it's something normal, due to a bug in previous domoticz version, the actual version use request lib. On the last version I m using the python request library, and it's something new for domoticz and surely your python version.

Try install the missing libs
```
sudo -H pip3 install requests
sudo -H pip install requests
```

It will install it for both python versions.

**Comment by erwan2345** [comment]
Hi, thks for your quick reply
Unfortunately, I updated Domoticz to last stable version and tried to install the missing libs you required but they were already there: it worst than before as now Domoticz in its last version does not start (no log to analyze what's wrong) with 1.0.9 plugin. When I restore the previous 1.0.7 version it is ok.
Difficult to figure out the pb.

**Comment by Smanar** [comment]
Perhaps your python version (domoticz use python 3) ? It's something news, it works in standard since the last stable (2 months), and now lot of plugin use this lib.

```
pi@raspberrypi:~ $ python --version
Python 2.7.13
pi@raspberrypi:~ $ python3 --version
Python 3.5.3
```
ATM, I m using V4.10935 Version, tell me is updating your python version is working, else I will try the actual domoticz beta version.

**Comment by erwan2345** [comment]
Ok: I was not able to upgrade Python at a higher level, normal, I was still under Jessie raspbian version.

I upgraded to Stretch (with finger crossed as usually this kind of upgrade generate some issues with my setup but finally the upgrade was ok. I have now the same Python version as you and domoticz is starting with the 1.0.9 plugin version. 
Thks for your advises.

Congratulations for this great plugin. I just have a code update proposal for some Ikea Tradfri devices: let me check with 1.0.9 version (I did some update on 1.0.7 that I have to test in 1.0.9) and I will let you know.

**Comment by Smanar** [comment]
Ha nice ^^. 
Go on beta branch (there is a combo box on main page).
After that, you can make all you want, open a file edit it, and github will make itself a fork on your github account (after a message), after that it will purpose you a pull request, but you can cancel it, and make it another time.
After that you can go on your github account, you will find the fork, you can edit all files, all you want, because they are yours, and after make a pull request, your fork > the beta.
It's hard to expain, but you will see, it instinctive.

Or you can just go on beta branch and fork it direcly, it's less instinctive, but you can't make mistake.

1 - go on beta branch
2 - make fork
3 - edit file on your fork
4- make pull request your fork > beta.
