### ISSUE TITLE
Wrong power consumption when there is more than one device

### ISSUE THREAD

**Issue by markhellegers** [Smanar/Domoticz-deCONZ#41]
I have two innr smartplugs that report the power consumption.
However, according to the logging they do this interleaved.
This causes the power from one plug to be reported in the consumption of the other.

I looked at the code and the problem seems to be that there is a buffercommand variable that assumes that the last reported power is for the device that is now reporting the consumption.
I am not sure what the best fix would be. I would guess best would be to know which device the power is registered for.

**Comment by Smanar** [comment]
Hello.
But you have not 2 websockets notifications, one for each devices, with "power" and "consumption" in all of them ?
Or 1 for "power" and 1 for "consumption"  (so 4 notifications in total) ?

**Comment by markhellegers** [comment]
Hello,

I see this in the logging. Hope that makes it clearer:

2020-01-04 20:29:16.685 (Conbee) ### WebSocket Data : {'e': 'changed', 'id': '2', 'r': 'sensors', 'state': {'consumption': 410, 'lastupdated': '2020-01-04T19:29:16'}, 't': 'event', 'uniqueid': '00:15:8d:00:03:42:a7:ab-01-0702'}
2020-01-04 20:29:16.686 (Conbee) ### Update device (Device A - Consumption 2) : {'nValue': 0, 'sValue': '0;410'}, IGNORED , no changes !
2020-01-04 20:29:17.588 (Conbee) ### WebSocket Data : {'e': 'changed', 'id': '3', 'r': 'sensors', 'state': {'current': 24, 'lastupdated': '2020-01-04T19:29:17', 'power': 3, 'voltage': 236}, 't': 'event', 'uniqueid': '00:15:8d:00:03:42:a7:ab-01-0b04'}
2020-01-04 20:29:17.589 (Conbee) ### Update device (Device A - Power) : {'nValue': 0, 'sValue': '3'}, IGNORED , no changes !
2020-01-04 20:29:18.491 (Conbee) ### WebSocket Data : {'e': 'changed', 'id': '4', 'r': 'sensors', 'state': {'consumption': 7850, 'lastupdated': '2020-01-04T19:29:18'}, 't': 'event', 'uniqueid': '00:15:8d:00:03:42:f0:8e-01-0702'}
2020-01-04 20:29:18.492 (Conbee) ### Update device (Device B - Consumption 4) : {'nValue': 0, 'sValue': '3;7850'}, IGNORED , no changes !
2020-01-04 20:29:19.394 (Conbee) ### WebSocket Data : {'e': 'changed', 'id': '5', 'r': 'sensors', 'state': {'current': 0, 'lastupdated': '2020-01-04T19:29:19', 'power': 0, 'voltage': 234}, 't': 'event', 'uniqueid': '00:15:8d:00:03:42:f0:8e-01-0b04'}
2020-01-04 20:29:19.395 (Conbee) ### Update device (Device B - Power) : {'nValue': 0, 'sValue': '0'}, IGNORED , no changes !

The overview in Domoticz says that the consumption device has type "General" and subtype "kWh", while the power device has type "Usage" and subtype "kWh".

Where can I check for "websocketnotifyall". I am still a bit new to Domoticz and the plugin.

**Comment by Smanar** [comment]
Don't worry, you have a message when you start the plugin about this option, but you have it to "true"

And yes, you are right, on your log you are updating" Device B - Consumption 4" with 'consumption' from the notification  but with the power from "Device A - Power".

In fact this device create 1 device for consumption 00:15:8d:00:03:42:a7:ab-01-0702 and one other for power 00:15:8d:00:03:42:a7:ab-01-0b04. Some other device use the same cluster 0b04 only.

Will be easy to correct, like i have said before, I just need to reset the field
>clear the field "buffercommand" and the start of the fonction ProcessAllState() 

But I need to make some tests, the device created in domoticz use both value power and consumption, in your situation power will be always 0, because you have it on other device. So I need to check how domoticz will be react.

**Comment by Smanar** [comment]
Ok so you have news files here https://github.com/Smanar/Domoticz-deCONZ/tree/beta

But you need to delete your device "(Device X - Consumption)" and restart the plugin after modification, devices will be re-created but as energy counter.
You can't have the same device than previously. Some plugs have power and consumption on same device on domoticz, but on your situation you will have them separated.

**Comment by NiklasOlofsson** [comment]
Noticed the same thing. I also have two innr plugs (SP 120). Beta looks much better.

**Comment by Smanar** [comment]
Typo corrected, thx :)

For counter, I m not sure yet ^^. I have, as choose at least

1 - General/Managed counter.
2 - General/KWh
3 - RFXmeter/RFX meter counter.

For sure I can have report and cost for the three. I have checked (on other hardware), but not sure it's working, I think we need at least 24h for a first result.

I need to use fakes values to use the 2, because it works with power and not consumption in reality.

But I haven't understand how they make cumul and use the "today" feature. The three can have it but the display seem random, only the 2 have this line all the time.

For the 2, it 's easy, this device works with power, so domoticz can make calculation itself. But for other, I think it's the device that make calculation and send directly a cumul.

For your server 18kw/h mean it use 750 W by hour so I hope you have a big server ?

**Comment by NiklasOlofsson** [comment]
18 kWh in total since plugging in the innr plug. The server use about 1.5-1.8 kWh/day. 

The devices named "Server" shown in my screenshots comes from this plugin (the beta branch)

**Comment by Smanar** [comment]
Ok, so I realy thing it's better to take General/Managed counter, this device is just a counter and only that.
If you take a look in the device Elmatare General/kwh, you have on the titlebar, a power and not a comsumption, and you have just under the consumption but just for the day.

Now just need to be sure the report and cost are working corectly.

**Comment by NiklasOlofsson** [comment]
Yes, I want to see the daily kWh usage to detect any strange deviations from day to day. The last image comes from the Domoticz app's widget.

The MySensors device called "Elmätare" is based on this:
https://www.mysensors.org/build/pulse_power

I have no history at all yet. The kWh-usage keeps going up as it should.

**Comment by NiklasOlofsson** [comment]
History and report is still empty.
If would be great iaf General, kWh could be used..
We need to send the total kWh usage and current watt usage to the device. I think the plug will report that info?

**Comment by Smanar** [comment]
Yep, but to use the General, kWh, I need to use special value for power, so I prefer use it in last try.

I have just find some new counter
![Domoticz_PowerUsage](https://user-images.githubusercontent.com/20152487/71915778-c049f700-317c-11ea-9dc1-06c19944367e.png)

It reset itself, and display today usage
But this one make addition itself, if you send 5kw/h then 10 kw/h it will display 15 and not 10.

So I m testing this one ATM
![aaa](https://user-images.githubusercontent.com/20152487/71916332-fe93e600-317d-11ea-9d70-09de2f959b50.jpg)
You have the actual consumption, and another value on title, but I haven't understand what is it (perhaps daily)

But I have history working on all of them, IDK why it's not working on your machine.

**Comment by NiklasOlofsson** [comment]
Some of the counter types use the division you set in Domoticz settings.
![Capture_Domoticz_-_Google_Chrome_2020-01-07_19-19-44_65310506](https://user-images.githubusercontent.com/4583709/71918505-b0351600-3182-11ea-9d94-af8fc8744e8f.png)

It's just a counter counting stuff. I used the RFXMeter counter in my old house. Counting pulses from the power meter. (10 000 pulses = 1kWh). It was just that. Counting the number of pulses and Domoticz divided it and made it show in kWh.

**Comment by Smanar** [comment]
But this one don't count, it just display the value I send to it !

I have created 2 widget with the same setting.
The first one display the value I send + 1 and the other the value I send - 1.

https://www.domoticz.com/forum/viewtopic.php?f=28&t=30815&p=233096#p233096

**Comment by NiklasOlofsson** [comment]
Not sure that i fully understand.

This can't be used? 
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Electricity_.28instant_and_counter.29

**Comment by Smanar** [comment]
Nope you are right ^^.
But your device create 2 widget in domoticz, one with only power and another with only consumption, it depend on device, and each of them receive it's new value.

The domoticz widget general/kwh is a good widget but I will not use at 100%. So I m searching a consumption widget, with daily information.

it exists on domoticz, and domoticz can manage them itself (reset every day for exemple), but I don't find how they  work.

The rfxmeter device look good, but it works realy strange during my test. You can check on your widget I think you already have one working ?
He have
- total consumption since you restart the device
- daily consumption
- report
- cost
It's just perfect for me, except the strange working mode ....

**Comment by NiklasOlofsson** [comment]
I don't have any rfxmeter device anymore. 

I do have one z-wave power plug.
Looks like this:
![Capture_Domoticz_-_Google_Chrome_2020-01-07_21-56-54_07134626](https://user-images.githubusercontent.com/4583709/71928844-a1f1f480-3198-11ea-938f-e28f47513148.png)

![Capture_Domoticz_-_Google_Chrome_2020-01-07_21-57-33_64878651](https://user-images.githubusercontent.com/4583709/71928889-b8984b80-3198-11ea-8a11-c92114ea9d05.png)

**Comment by Smanar** [comment]
Give me some days (waiting for return from domoticz community) to make a try.

The rfxmeter will not look like the Zwave kwh Meter. But it will more usable, for exemple you will have total consumption (not present in zwave widget), the future device will be a widget made just for consumption. IDK how will be the report but I realy think I will be fine.

If, realy, the future widget will be bad, I will make with the general/kwh but I see lot of disadvantages with it.

**Comment by NiklasOlofsson** [comment]
No problem. I can create my own as long as I have access to current watt and k(W)h value. 

Total usage checked using the reports. My energy meter for the whole house is at 14028.009 kWh. Not much of use to see the total usage in the widget. 😉

**Comment by Smanar** [comment]
Ok so I have a new counter to try > https://github.com/Smanar/Domoticz-deCONZ/commit/87b3c8dedfa2770acee325354de953f26f0c4c54#diff-66c71ea3faaa52c277917c951aa67921

**Good point:**
- Cumul
- Daily consumption
- Report for day/week/month/year
- Cost
- On device list it looks like the general/kwh

**Bad point**
- It works strangely

I have updated my domoticz version, because on previous It log bad value when the counter reset. The widget do the math : Today = actual - previous, but if the counter reset you have actual = 0 so a negative value > bug.
I m making test since 2 / 3 days, it seem working now, but you need at least 24h to have correct data.

Pls tell me how you fell this one !

**Comment by NiklasOlofsson** [comment]
Seems to work just fine. Will evaluate in a couple of days with some history to talk about.

Thanks!

**Comment by Smanar** [comment]
So, no problem, how is the device ?

If you have same probleme than me with "big number", can you make a screeshoot for I make an issue.

**Comment by NiklasOlofsson** [comment]
Looking good here. No problem with big numbers.

**Comment by Smanar** [comment]
And yes, it's that the problem ^^.
When you power off the plugin, the counter restart to 0, this is something normal on this device I think, but on domoticz side sometime it works, but sometime the first value is a big one, it will be corrected at first next good value, but on old domoticz version the "fake value" was stored in database, and make report totaly useless.

I have make a post about this https://www.domoticz.com/forum/viewtopic.php?f=28&t=30815&p=233096#p233096
But without answer, so if you still have the problem, I will make an issue.

I did not have the problem on my last tries, but tell me if you see it.

**Comment by NiklasOlofsson** [comment]
Just a power cut. Strong winds outside today.

![Capture_Domoticz_-_Google_Chrome_2020-02-09_20-43-35_43425232](https://user-images.githubusercontent.com/4583709/74108693-3925df80-4b7d-11ea-9c99-ead038986f6d.png)

This probably happens when the counter in the plug resets to 0 after power cut..

**Comment by Smanar** [comment]
It haven't reset ?
The bug is from domoticz code, they just make

`total_day = total_send - total_min_today`

And I send the cumulated value you have on the device, 828 on your screenshot.

If you make a reset, the send value decomes 0 so you have

`total_day = 0 -  another_value`

And the variable used can't be negative, so you have a "big number".

I think you had a situation where the plugin have received a consumption = 0 (without reset, just bad value). So in this situation, I m agree it's a bug from the plugin (or perhaps deconz, but without log, We'll never know) but if you make a reset you will same problem, so for me, the domoticz code need to be patched too.

I m making a domoticz issue ATM.

**Comment by Smanar** [comment]
@NiklasOlofsson 
I m trying to simulate your bug, but I can't.

Can you explain what have happened ?
You have a power cut during some hours, with the plug and domoticz off ?
