### ISSUE TITLE
Combine sensors

### ISSUE THREAD

**Issue by dennisb1** [Smanar/Domoticz-deCONZ#50]
I have a Temp sensor from Xiaomi.

When im reading this out in Domoticz i get 3 devices. Temp, Humidity and Preasure.

Why is this not combinend? With a power meter i have the same issue.
When looking in deCONZ i see it as one device and this is the way i want it without any LUA scripts or whatever to get this result.

What am i doing wrong?

**Comment by Smanar** [comment]
Hello,
If you look in deconz I can promise you will see 3 sensors too.
You have only 1 device in deconz but in the API you will have 3 sensors, one by endpoint. So you will have for exemple

00:15:8d:00:02:f3:AA:57-01-0402 for temperature
00:15:8d:00:02:f3:AA:57-01-0405 for humidity
00:15:8d:00:02:f3:AA:57-01-0403 for pressure

00:15:8d:00:02:f3:AA:57 is the mac adress.
01 is the endpoint.
0403 is the cluster.

For temperature I can understand the problem, but it same for presence detection + luxmeter and for those I think you will prefer to separete them.

To group them there is an easy LUA script > https://github.com/Smanar/Domoticz-deCONZ/wiki/Example-to-make-a-LUA-script-to-mix-temperature-humidity-barometer-on-the-same-sensor

**Comment by dennisb1** [comment]
Is this not making a huge CPU usage when using this?

**Comment by Smanar** [comment]
No the papoo script is realy light.
But 20 % is realy hight.

I m always unders 5% with domoticz and deconz on the same machine.

Domoticz is a light application too, not normal it increase the cpu usage by 15 %

**Comment by dennisb1** [comment]
This is what happens when the script from papoo is running. 
Its on a Raspberry PI 3 B+
When i turn the script off instant the CPU drops.

https://ibb.co/vqqJnKt
https://ibb.co/4gqky2N

**Comment by Smanar** [comment]
Ok, it s not normal.
Pls wait some days before using this script, I will try to pm papoo for more informations.

**Comment by Smanar** [comment]
Back.

So papoo is agree with me it's not possible.
If it's your first dzevent script, you can have more CPU use because Domoticz need to load the dzevent engine but not 13% more 

But I m trying it ATM on my machine, the script is invisible (and it's my only dzevent script)

How have you create this script on domoticz ?
I have used the buildin engine in setting / more options / event > new dzevent / device and it have created a file in /home/pi/domoticz/scripts/dzVents/generated_scripts

**Comment by dennisb1** [comment]
Your correct. This is my first script running (other is a blockly script)

Yes i have created this script using the new dzevent option within Domoticz

I dont have debug log on, its on Error/Minimal/Informal but even lowering dont make a diffrance. I dont see any logging even when i turn debug on in the log section.

But... the scripts works, it updates 2 sensors at this moment with baro/temp/humidity
With the CPU i only see it dropping when i turn off this script. Sure, i got the cpu power on the Rpi3B+ but still i find this very strange.

Im afraid it will raise even more when i find a script to combine the Watt/Kwh script for the Innr power plug

**Comment by Smanar** [comment]
On my side I have max 1% more cpu usage with the script (and with enabling dzevent in same time).

I have debug on "silent", else on "debug" It trigger for all devices change, so it spam the log windows. Not normal you don't see any change too !

Can you try with a fake dzevent script, aminiaml one like 

```
return
{
    on =
    {
        devices = { 'Room switch'}
    },
    execute = function(domoticz, roomSwitch)
        if (roomSwitch.active and domoticz.devices('Living room').temperature > 18) then
        domoticz.devices('Another switch').switchOn()
        domoticz.notify('This rocks!',
                        'Turns out that it is getting warm here',
                        domoticz.PRIORITY_LOW)
        end
}
```

To see if the problem is from the script itself or the DZevent engine loading ?

How many temperature sensor have you ? If you only have few of them, you can use a lua script, perhaps better result.

**Comment by dennisb1** [comment]
When i turn it off its back to 3-4% max.
When i try your test script the same happens, its 30-35% cpu.

I have 4 temp sensors and i still need to get a script for the innr power plug to combine the wattage and kwh total so i'm not done yet

Thanks for so far!

**Comment by Smanar** [comment]
Ok, so I think you can ask in domoticz forum for information.
This script is realy basic, not normal you increase your cpu consommation by 30% just because you have enabled the dzevent.
For me there is a problem either in your configuration either in domoticz itself.

The only thing I know than can provoke that is the debugging (or logs) enabled.

**Comment by dennisb1** [comment]
Thank you, i will go try it there!
