### ISSUE TITLE
Frontend Tab not working properly

### ISSUE THREAD

**Issue by Faewks** [Smanar/Domoticz-deCONZ#88]
Hi all,
I've seen the "recent" change for the domoticz frontend, which I absolutely appreciate,  but I can't get it to work. It is stuck on "Loading...".
![domoticz_deconz](https://user-images.githubusercontent.com/78206368/106262753-bda4be80-6223-11eb-85a8-6f915c8bbad8.PNG)

When I get into "Configure Plugin" and want to add the gateway password it returns "null". I've checked my password by logging into the phoscon app and all works fine on this end. 

Here are my questions: 

- Do I need to change something outside of domoticz/inside of domoticz to enable this tab?
- Do I actually need to add the phoscon gateway password here since I already know the API key?
- If so: Are there any characters that can throw this error if they are used in a password?

If I can provide an error log on this situation please explain me how, since if I set the plugin option to "Debug: Debug info only" I don't receive any error.

Sincerely, 
Faewks.

**Comment by Smanar** [comment]
>    Do I need to change something outside of domoticz/inside of domoticz to enable this tab?
no

>    Do I actually need to add the phoscon gateway password here since I already know the API key?
Only in the plugin configuration

>    If so: Are there any characters that can throw this error if they are used in a password?
If the plugin is working, no more to do


For this feature work you need 2 things, a recent domoticz version, but you need to use http, instead of http.
There is a security to block http request inside a https page, this is some ugly workaround, but the better method is waiting for a https support in deconz.
But use http request for domoticz works fine.

**Comment by Faewks** [comment]
Ok, thanks for the explanation! 
Can confirm, works over http.
